import { Play } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import MainContents from "@/components/MainContents";
import { DataProvider } from "@/contexte/DataContext";
import "@/globals.css";

const play = Play({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Progress App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr" className={play.className}>
      <DataProvider>
        <body className="flex flex-col items-center ">
          <Header />
          <MainContents>{children}</MainContents>
          <Footer />
        </body>
      </DataProvider>
    </html>
  );
}
